### ISSUE TITLE
Want to see html entities on html view.

### ISSUE THREAD

**Issue by TheAustinMunro** [Waxolunist/bootstrap3-wysihtml5-bower#101]
Is there a way when you switch to html view to specify what tags you would like to still see.

ie I want a custom tag <inline>words</inline> to show just like that on the html view, not like &lt;inline&gt;words&lt;/inline&gt;

I've been trying to track down the function that replaces "<" with "&lt;" but can't seem to find it. 

Any help is appreciated.

**Comment by Waxolunist** [comment]
Please open this issue at https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg

This repo is deprecated in favor of the above.
