### ISSUE TITLE
img button inserts empty tag

### ISSUE THREAD

**Issue by guyaloni** [Waxolunist/bootstrap3-wysihtml5-bower#102]
I have the editor integrated with Rails-4 and bootstrap-3.

I use the editor in few places. I have a couple of places where everything works fine, including the link button which inserts the link correctly.
However, the image button inserts the following code:

    <img alt="">

I can insert an image directly activating the html edit button, but then I lose the whole idea of the editor.
Some ideas?

**Comment by Rub4ek** [comment]
Same for me, with version 0.3.3

**Comment by wilsonfalai** [comment]
Same for me too.

**Comment by alexander-torosh** [comment]
+1 for this issue

**Comment by Waxolunist** [comment]
Please open this issue at https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg

This repo is deprecated in favor of the above.
