### ISSUE TITLE
color not working

### ISSUE THREAD

**Issue by ryan2johnson9** [Waxolunist/bootstrap3-wysihtml5-bower#103]
Hi,

This is a follow up on #68. He said to add
 
    stylesheets: ["{{ STATIC_URL }}css/bootstrap3-wysiwyg5-color.css"] as a paramater

but I could not find where that css file was. 

How do I know where the "css/bootstrap3-wysiwyg5-color.css" file is on ,my project?

I am using bootstrap-sass gem and I use

    @import "bootstrap-sprockets";
    @import "bootstrap";

in one of my css.scss files which is required into application.css.

I'm not sure if I'm supposed to change {{STATIC_URL }} to something.

And wouldn't the path to css/bootstrap3-wysiwyg5-color.css be different on production and development?

**Comment by Waxolunist** [comment]
Please open this issue at https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg

This repo is deprecated in favor of the above.
