### ISSUE TITLE
Error cohabitating with requirejs

### ISSUE THREAD

**Issue by atuttle** [Waxolunist/bootstrap3-wysihtml5-bower#105]
I've recently added RequireJS to my project but don't want to use it to manage WYSIHTML5 (nor many other things).

Trying to include it outside of requirejs usage (e.g. just in a `<script></script>` tag on the page) when requirejs is also running, I get the following error:

    Uncaught Error: Mismatched anonymous define() module: function (){return E.amd=!0,E}

Based on release dates and source comments I think I'm on version 0.3.2 of **bootstrap3-wysihtml5-bower**. Looking at the minified js for `.all.min.js` I see two calls to `define()`, the first of which is "anonymous" (doesn't specify a module name), and the second uses the name "bootstrap.wysihtml5".

It doesn't look like this AMD stuff is in the file currently in the master branch. Was it removed?

I also found #40, but that's obviously kind of old now.

Any advice? Will upgrading likely resolve my AMD errors? (Remember, I don't care if a wysihtml5 module is registered...) Are there any big changes between 0.3.2 and 0.3.3 that I would have to look out for?

**Comment by Waxolunist** [comment]
Please open this issue at https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg

This repo is deprecated in favor of the above.
