### ISSUE TITLE
Need a way to reliably destroy the editor

### ISSUE THREAD

**Issue by blargism** [Waxolunist/bootstrap3-wysihtml5-bower#106]
On single page apps, leaving big objects lying around without removing event listeners and de-referencing things can create memory problems eventually.  In my case I'll be re-creating the editor often, I'd like to know that I am not leaving tons of event listeners and partially referenced objects lying around.

If this is already supported, can you please make sure it's documented.  I was not able to find it anywhere.

Thanks so much.

**Comment by Waxolunist** [comment]
Please open this issue at https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg

This repo is deprecated in favor of the above.
