### ISSUE TITLE
Focus move up one line after press enter key

### ISSUE THREAD

**Issue by Debiprasad** [Waxolunist/bootstrap3-wysihtml5-bower#107]
This issue is in the reference of the issue on the [original bootstrap plugin](https://github.com/jhollingworth/bootstrap-wysihtml5/issues/344). 

I replaced that plugin with this plugin. But still I am encountering the same issue.

**Comment by Debiprasad** [comment]
If I use both wysihtml5-0.3.0.min.js and bootstrap3-wysihtml5.min.js, then it works fine. But if I use only bootstrap3-wysihtml5.all.min.js, I experience the issue.

**Comment by Debiprasad** [comment]
I was wrong when I said that it's working fine with wysihtml5-0.3.0.min.js and bootstrap3-wysihtml5.min.js. In fact nothing works with that. I saw a plain textarea and thought the issue is solved.

**Comment by Debiprasad** [comment]
It started working fine with bootstrap3-wysihtml5.all.min.js again. I guess there was some issue with caching, even though I tried to clear the cache before using it.

**Comment by Waxolunist** [comment]
Please open this issue at https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg

This repo is deprecated in favor of the above.
