### ISSUE TITLE
Color button in IE

### ISSUE THREAD

**Issue by AlexandrM** [Waxolunist/bootstrap3-wysihtml5-bower#109]
In IE (internet explorer) not work color button

1. Select text
2. Click on select color dropdown
2.1. In Chrome text selection stay on
2.2. In IE text selection clear
3. On select color 
3.1. Chrome - color changed
3.1. IE - color unchanged

I think problem in selection clear.

**Comment by Waxolunist** [comment]
Please open this issue at https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg

This repo is deprecated in favor of the above.
