### ISSUE TITLE
Update bootstrap dependency to 3.3 or greater?

### ISSUE THREAD

**Issue by dajo82** [Waxolunist/bootstrap3-wysihtml5-bower#110]
Hi, I was trying to install via composer (which calls bower), but it failed because of the dependency on bootstrap 3.1.0. Could you update to 3.3? thx!

**Comment by miguelmich** [comment]
Same here

**Comment by ideaoforder** [comment]
+1

**Comment by Waxolunist** [comment]
I am sorry. 

See readme. This repo is deprecated in favor of https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg.
