### ISSUE TITLE
Pasting a link causes weird double-spacing issue

### ISSUE THREAD

**Issue by adampmoss** [Waxolunist/bootstrap3-wysihtml5-bower#111]
If you try pasting a link in your demo: http://bootstrap-wysiwyg.github.io/bootstrap3-wysiwyg/ then press space bar and carry on writing you'll notice that it puts a double-space - the normal one and a highlighted nbsp; character. Doing this then causes further issues when editing text within the editor.

I tried to fix but couldn't find the cause of the problem.

**Comment by Waxolunist** [comment]
Please open this issue at https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg

This repo is deprecated in favor of the above.
