### ISSUE TITLE
Change the dependency from non-official "components-font-awesome" to the official "fontawesome"

### ISSUE THREAD

**Issue by Haixing-Hu** [Waxolunist/bootstrap3-wysihtml5-bower#112]
Hi,

Currently the bower package of this project depends on the non-official "components-font-awesome", but there is an official  "fontawesome". 

Could you please change the dependency from "components-font-awesome" to "fontawesome"?

Thanks a lot.

**Comment by Waxolunist** [comment]
Please open this issue at https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg

This repo is deprecated in favor of the above.
