### ISSUE TITLE
Deprecate this repo

### ISSUE THREAD

**Issue by andrewkouri** [Waxolunist/bootstrap3-wysihtml5-bower#113]
You should add a big bold link to the new joint repo in the README

**Comment by koppor** [comment]
Could you provide the link? ^^

**Comment by thoresuenert** [comment]
This Repo is deprecated?
Please share your information.

**Comment by andrewkouri** [comment]
https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg

**Comment by Waxolunist** [comment]
Sorry. Always thought I've already done that. I will do it ASAP.
