### ISSUE TITLE
Text isn't formatted on bootstrap modal show

### ISSUE THREAD

**Issue by kennedc** [Waxolunist/bootstrap3-wysihtml5-bower#114]
I'm using your editor in a bootstrap modal, but it doesn't format the text when opened, so all i see is regular text without linebreaks or white spaces. Is there anyway to format the text, so it looks correct in the editor on show?
This is the code i use for opening the editor:

    $("#myModal").on("shown.bs.modal", function () { 
      $('#textarea2').wysihtml5();
      $('#textarea2').html($( "#info" ).text());
});

    $('#myModal').on('hidden.bs.modal', function () {
        $('.wysihtml5-sandbox, .wysihtml5-toolbar').remove();
        $('#textarea2').show();
    });
});

//Kenneth

**Comment by Waxolunist** [comment]
Please report to https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg 
This one here is deprecated.
