### ISSUE TITLE
wysihtml5 is not a function

### ISSUE THREAD

**Issue by JohnMcAvinue** [Waxolunist/bootstrap3-wysihtml5-bower#115]
I'm pretty sure I have the required files referenced but think there's a version mismatch as I'm getting the following error when I try to initalise my text area:

Uncaught TypeError: $(...).wysihtml5 is not a function

The error is thrown on this line:

$('#WelcomeText').wysihtml5();

I have the latest version of jQuery referenced (v2.1.4) and Bootstrap (v3.1.1).

Here's my JS references in totality:

<pre>&lt;script src=&quot;/Scripts/jquery-2.1.4.js&quot;&gt;&lt;/script&gt;
&lt;script src=&quot;/Scripts/jquery.validate.js&quot;&gt;&lt;/script&gt;
&lt;script src=&quot;/Scripts/jquery.validate.unobtrusive.js&quot;&gt;&lt;/script&gt;
&lt;script src=&quot;/Content/admin/js/libs/bootstrap.js&quot;&gt;&lt;/script&gt;
&lt;script src=&quot;/Content/admin/js/mvpready-core.js&quot;&gt;&lt;/script&gt;
&lt;script src=&quot;/Content/admin/js/mvpready-admin.js&quot;&gt;&lt;/script&gt;
&lt;script src=&quot;/Content/admin/js/libs/moment-with-locales.js&quot;&gt;&lt;/script&gt;
&lt;script src=&quot;/Content/admin/js/libs/jquery.blockUI.js&quot;&gt;&lt;/script&gt;
&lt;script src=&quot;/Content/admin/js/plugins/dataTables/jquery.dataTables.js&quot;&gt;&lt;/script&gt;
&lt;script src=&quot;/Content/admin/js/plugins/dataTables/dataTables.bootstrap.js&quot;&gt;&lt;/script&gt;
&lt;script src=&quot;/Content/admin/js/libs/bootstrap-datepicker.js&quot;&gt;&lt;/script&gt;
&lt;script src=&quot;/Content/admin/js/libs/knockout-3.2.0.js&quot;&gt;&lt;/script&gt;
&lt;script src=&quot;/Content/admin/js/custom/knockout-ext.js&quot;&gt;&lt;/script&gt;
&lt;script src=&quot;/Content/admin/js/custom/common.js&quot;&gt;&lt;/script&gt;
&lt;script src=&quot;/Content/admin/js/custom/app.js&quot;&gt;&lt;/script&gt;
&lt;script src=&quot;/Content/admin/js/custom/audit-history.js&quot;&gt;&lt;/script&gt;
&lt;script src=&quot;/Content/admin/js/custom/notifications.js&quot;&gt;&lt;/script&gt;
&lt;script src=&quot;/Content/admin/js/custom/logged-in-user.js&quot;&gt;&lt;/script&gt;    
 &lt;script src=&quot;/Content/admin/js/libs/require.js&quot;&gt;&lt;/script&gt;
&lt;script src=&quot;/Content/admin/js/libs/bootstrap3-wysiwyg/bootstrap3-wysihtml5.js&quot;&gt;&lt;/script&gt;</pre>

Is there something that I'm missing here?

Thanks

**Comment by ideaoforder** [comment]
+1

**Comment by Waxolunist** [comment]
Sorry that I can't help at the moment. Please ask over here: 

 https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg

This repo is deprecated.
