### ISSUE TITLE
send value to editor from JS

### ISSUE THREAD

**Issue by ddmitr** [Waxolunist/bootstrap3-wysihtml5-bower#45]
Can't add text to editor. 

```
$('#editor').val('Some text');
```

But this does not work.

**Comment by mleziva** [comment]
This does not work using an asp textbox:

$("#text_area").wysihtml5();
var editorObj = $("#text_area").data('wysihtml5');
var editor = editorObj.editor;
editor.setValue(html_goes_here);

It says that the editor is undefined. I have linked the bootstrap3-wysihtml5.all.min, jquery, and bootstrap.js.min.

**Comment by knickers** [comment]
Thank you @abishekrsrikaanth you saved my day! Is there any documentation about the methods available on that editor object?

**Comment by Waxolunist** [comment]
Basically it is a version of this one: http://wysihtml.com/

**Comment by yuhua-chen** [comment]
Thanks @abishekrsrikaanth ! you saved my day as well. works like a charm.

**Comment by pacozaa** [comment]
Why @abishekrsrikaanth  answer is not on readme?

**Comment by gabisajr** [comment]
`$('iframe').contents().find('.wysihtml5-editor').html('your new content  here');`
