### ISSUE TITLE
Button size option not supported yet?

### ISSUE THREAD

**Issue by luboskmetko** [Waxolunist/bootstrap3-wysihtml5-bower#58]
Hey,

first of all, nice job on this editor!

I was trying to use button size option but it doesn't work. Isn't it implemented yet or am I doing something wrong? 

Using `"size": "sm"` for example but doesn't seem appropriate Bootstrap classes are generated in the code (only `"btn  btn-default"`). Editor and other options normally work.

Thanks!

**Comment by rizkysyaiful** [comment]
@Waxolunist I think you should update the doc here -> https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg#buttons
